server:
  port: 83

spring:
  application:
    name: nacos-order-provider
  cloud:
    nacos:
      discovery:
        server-addr: liaoqingting.com:8848

management:
  endpoints:
    web:
      exposure:
        include: '*'

#消费者将要去访问的为服务名称
service-url:
  nacos-user-service: http://nacos-payment-provider
