server:
  port: 84

spring:
  application:
    name: nacos-feign-order-provider
  cloud:
    nacos:
      discovery:
        server-addr: liaoqingting.com:8848

management:
  endpoints:
    web:
      exposure:
        include: '*'